; AgroSensor OGB · Invernadero inteligente
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0

[env:invernadero]

[env:wokwi]
build_flags = -DWOKWI_SIMULATION
