; AgroSensor OGB · Nodo sensor
; pio run -e nodo   -> hardware real (BME opcional, BH1750)
; pio run -e wokwi  -> simulación (potenciómetro + LDR + DHT22)

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0

[env:nodo]
lib_deps =
    ${env.lib_deps}
    claws/BH1750@^1.3.0

[env:wokwi]
build_flags = -DWOKWI_SIMULATION
