# Simulación local con la extensión Wokwi de VS Code
# Requiere compilar primero: pio run -e wokwi
[wokwi]
version = 1
firmware = "../.pio/build/wokwi/firmware.bin"
elf = "../.pio/build/wokwi/firmware.elf"
